apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: birds
  namespace: test
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: birds
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  #serviceAccountName: tap-default
  source:
    git:
      url: https://github.com/sample-accelerators/birds
      ref:
        branch: main

